version: "3.9"
services:
  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    container_name: monitor
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    environment:
      - PORT=8001
      - APP_NAME=service-a
      - MONITOR_URL=http://monitor:3000
      - MEM_THRESHOLD=95
      - CPU_THRESHOLD=95

  service-a1:
    build:
      context: ./serviceA
      dockerfile: Dockerfile
    container_name: service-a1
    restart: always
    ports:
      - "8000:8000"
    networks:
      - monitor-net
    depends_on:
      - monitor
    environment:
      - PORT=8000
      - APP_NAME=service-a
      - MONITOR_URL=http://monitor:3000
      - MEM_THRESHOLD=95
      - CPU_THRESHOLD=95
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

  service-a2:
    build:
      context: ./serviceA
      dockerfile: Dockerfile
    container_name: service-a2
    restart: always
    ports:
      - "8001:8001"
    networks:
      - monitor-net
    depends_on:
      - monitor
    environment:
      - PORT=8001
      - APP_NAME=service-a
      - MONITOR_URL=http://monitor:3000
      - MEM_THRESHOLD=95
      - CPU_THRESHOLD=95
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

networks:
  monitor-net:
    driver: bridge
